### ISSUE TITLE
prompt-base vs prompt-question

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/enquirer-question#1]
`prompt-base` accepts `transform` while `prompt-question` does not; instead requiring `options.transform`. It's kinda weird.

**Comment by jonschlinkert** [comment]
how are you using `prompt-question`?

edit: please try to provide more background information on what you're doing etc. Otherwise, we'll need to keep going back and forth. My reaction to this was "Why would he need to use prompt-question at all?".

**Comment by stevenvachon** [comment]
Oops, my bad. Thank you for the quick response!!

edit: I wasn't using this library directly, but via Enquirer's `question()`.

**Comment by jonschlinkert** [comment]
np
